### ISSUE TITLE
ImportError: cannot import name 'RNNCell'

### ISSUE THREAD

**Issue by loveJasmine** [barronalex/Dynamic-Memory-Networks-in-TensorFlow#6]
(venv) ali-186590cc37a5:Dynamic-Memory-Networks-in-TensorFlow $ python3
Python 3.6.0 (default, Mar  4 2017, 12:32:34) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
'1.1.0'
>>> quit()
(venv) ali-186590cc37a5:Dynamic-Memory-Networks-in-TensorFlow$ python3 dmn_test.py -b 2

aname
the value of ccc is   this is a string
on func:test at file:andy_common.py #28
the value of aname is   111111
on func:<module> at file:dmn_test.py #24
Traceback (most recent call last):
  File "dmn_test.py", line 25, in <module>
    from dmn_plus import Config
  File "//Dynamic-Memory-Networks-in-TensorFlow/dmn_plus.py", line 13, in <module>
    from attention_gru_cell import AttentionGRUCell
  File "//Dynamic-Memory-Networks-in-TensorFlow/attention_gru_cell.py", line 24, in <module>
    from tensorflow.python.ops.rnn_cell_impl import RNNCell
ImportError: cannot import name 'RNNCell'
(venv) ali-186590cc37a5:Dynamic-Memory-Networks-in-TensorFlow $

**Comment by loveJasmine** [comment]
tf1.2 is ok
