### ISSUE TITLE
_add_gradient_noise error

### ISSUE THREAD

**Issue by papower1** [barronalex/Dynamic-Memory-Networks-in-TensorFlow#8]
pip list

> backports.weakref (1.0rc1)
bleach (1.5.0)
funcsigs (1.0.2)
html5lib (0.9999999)
Markdown (2.2.0)
mock (2.0.0)
nltk (3.2.5)
numpy (1.13.1)
pbr (3.1.1)
pip (9.0.1)
protobuf (3.4.0)
setuptools (36.3.0)
six (1.10.0)
tensorflow-gpu (1.2.0)
Werkzeug (0.12.2)
wheel (0.29.0)

traceback

> Traceback (most recent call last):
  File "dmn_train.py", line 51, in <module>
    model = DMN_PLUS(config)
  File "/home/papower1/notebook/Dynamic-Memory-Networks-in-TensorFlow-master/dmn_plus.py", line 587, in __init__
    self.train_step = self.add_training_op(self.calculate_loss)
  File "/home/papower1/notebook/Dynamic-Memory-Networks-in-TensorFlow-master/dmn_plus.py", line 187, in add_training_op
    gvs = [(_add_gradient_noise(grad), var) for grad, var in gvs]
  File "/home/papower1/notebook/Dynamic-Memory-Networks-in-TensorFlow-master/dmn_plus.py", line 72, in _add_gradient_noise
    t = tf.convert_to_tensor(t, name="t")
  File "/home/papower1/notebook/Dynamic-Memory-Networks-in-TensorFlow-master/venv/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 676, in convert_to_tensor
    as_ref=False)
  File "/home/papower1/notebook/Dynamic-Memory-Networks-in-TensorFlow-master/venv/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 741, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/papower1/notebook/Dynamic-Memory-Networks-in-TensorFlow-master/venv/local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 113, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/papower1/notebook/Dynamic-Memory-Networks-in-TensorFlow-master/venv/local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/papower1/notebook/Dynamic-Memory-Networks-in-TensorFlow-master/venv/local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 364, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.

I did comment tf.convert_to_tensor line and no luck.
Now I'm doing debug...

**Comment by barronalex** [comment]
I didn't get an error running TF 1.4 with python 2.7, but there was a warning so I simplified the function a bit in 52db468. Let me know if this is still a problem.
